algoritmo "LEITURA_V1"
tipo
  CAD_ALUNO = registro
                NOME  : caracter
                TURMA : caracter
                SALA  : inteiro
                NOTA1 : real
                NOTA2 : real
                NOTA3 : real
                NOTA4 : real
              fimregistro
var
  ALUNO : cad_aluno
inicio
  leia(ALUNO.NOME)
  leia(ALUNO.TURMA)
  leia(ALUNO.SALA)
  leia(ALUNO.NOTA1)
  leia(ALUNO.NOTA2)
  leia(ALUNO.NOTA3)
  leia(ALUNO.NOTA4)
fimalgoritmo
